export const TOGGLE_SIDEBAR_MENU = "TOGGLE_SIDEBAR_MENU";
export const SET_SIDEBAR_SKIN = "SET_SIDEBAR_SKIN";
export const TOGGLE_MENU_CHILD_INDENT = "TOGGLE_MENU_CHILD_INDENT";
export const POSTS_SUCCESS = "POSTS_SUCCESS";
export const PATCH_SUCCESS = "PATCH_SUCCESS";
export const LOADING = "LOADING";
